services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.hub
      args:
        JUPYTERHUB_VERSION: latest
    image: jupyterhub
    container_name: jupyterhub
    restart: always
    networks:
      - jupyterhub-network
    volumes:
      # JupyterHub configuration
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Docker socket so DockerSpawner can create containers
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Persist JupyterHub database & cookie secret
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"
    environment:
      # Admin user
      JUPYTERHUB_ADMIN: admin
      # Network name for spawned containers
      DOCKER_NETWORK_NAME: jupyterhub-network
      # Image to spawn for single-user notebooks
      DOCKER_NOTEBOOK_IMAGE: jupyter-elyra-multienv:latest
      # Notebook directory in the single-user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work

  # Build-only service for the single-user image
  singleuser-image:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: jupyter-elyra-multienv:latest
    container_name: singleuser-build
    networks:
      - jupyterhub-network
    # We don't actually run this container, just build the image
    entrypoint: /bin/true

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network