ARG JUPYTERHUB_VERSION=latest
FROM quay.io/jupyterhub/jupyterhub:$JUPYTERHUB_VERSION

# Install spawners/authenticators as needed
RUN python3 -m pip install --no-cache-dir \
    dockerspawner \
    jupyterhub-nativeauthenticator

# Launch JupyterHub with your config file
CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]